server:
  port: 8080
spring:
  application:
    name: pq
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pq?useSSL=false&serverTimezone=UTC
    username: root
    password: 041205gy
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.pq.entity # 别名扫描包
  configuration:
    map-underscore-to-camel-case: false
logging:
  level:
    com.pq: debug